# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{resque_mailer}
  s.version = "1.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Gert Thiel", "Nick Plante", "Marcin Kulik"]
  s.date = %q{2011-03-03}
  s.description = %q{Rails plugin for sending asynchronous email with ActionMailer and Resque (resque-igo, MongoDB)}
  s.email = %q{GertThiel@gmx.net}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".gitignore",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/resque_mailer.rb",
    "lib/resque_mailer/common.rb",
    "lib/resque_mailer/rails2.rb",
    "lib/resque_mailer/rails3.rb",
    "rails/init.rb",
    "resque_mailer.gemspec",
    "spec/common_spec.rb",
    "spec/rails2_spec.rb",
    "spec/rails3_spec.rb",
    "spec/spec.opts",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{https://github.com/GertThiel/resque_mailer}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Rails plugin for sending asynchronous email with ActionMailer and Resque (resque-igo, MongoDB)}
  s.test_files = [
    "spec/common_spec.rb",
    "spec/rails2_spec.rb",
    "spec/rails3_spec.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_development_dependency(%q<resque-igo>, ["~> 1.12.8"])
      s.add_development_dependency(%q<actionmailer>, [">= 2.3.4"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<resque-igo>, ["~> 1.12.8"])
      s.add_dependency(%q<actionmailer>, [">= 2.3.4"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<resque-igo>, ["~> 1.12.8"])
    s.add_dependency(%q<actionmailer>, [">= 2.3.4"])
  end
end

